version: '3.9'

services:
  postgres-peekandcloppenburg:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=peekandcloppenburgdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-peekandcloppenburg:/var/lib/postgresql/data

volumes:
  postgres-peekandcloppenburg:
